version: '3'
services:
  database:
    image: postgres:15-alpine
    container_name: beringlab_database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - beringlab_db_volume:/var/lib/postgresql/data/pgdata
  broker:
    image: redis:7-alpine
    container_name: beringlab_broker
    depends_on:
      - database
    restart: always
  worker:
    build: .
    entrypoint: celery -A beringlab worker -l debug
    depends_on:
      - broker
      - database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: beringlab_worker
    restart: always
  api:
    build: .
    container_name: beringlab_api
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8888:8888
    depends_on:
      - database

volumes:
  beringlab_db_volume:
